This example showcases, how user can provide imput in SI units.

In [1]:
from py_files.data_prep import *
from py_files.data_utils import *
from py_files.mainframe import *
from py_files.data_example import *
import matplotlib.pyplot as plt

In [2]:
user_array = user_table_example()[3:]
properties_table_raw = properties_table_example()

In [3]:
for i, unit in enumerate(['imperial', 'si']):
    print(unit)
    print('-'*10)
    print(user_array[i], '\n')

imperial
----------
[[4.000e+00 3.800e+00 5.000e-01 8.310e+02]
 [3.000e+00 2.800e+00 5.000e-01 2.727e+03]
 [2.000e+00 1.800e+00 5.000e-01 2.070e+02]]

si
----------
[[4.00e+00 3.80e+00 5.00e-01 2.53e+02]
 [3.00e+00 2.80e+00 5.00e-01 8.31e+02]
 [2.00e+00 1.80e+00 5.00e-01 6.30e+01]]

In [4]:
for i, unit in enumerate(['imperial', 'si']):
    print(unit)
    print('-'*10)
    print(properties_table_raw[i], '\n')

imperial
----------
inlet_temperature          1800.000
ambient_temperature          68.000
mass_flow_rate            24155.000
specific_heat_capacity        1.000
k_pipe                        9.700
k_insulation                  0.025
solar_flux                   50.000
emissivity                    1.000
dtype: float64

si
----------
inlet_temperature           982.0000
ambient_temperature          20.0000
mass_flow_rate            10956.5000
specific_heat_capacity        4.1860
k_pipe                       16.8000
k_insulation                  0.0433
solar_flux                  157.7000
emissivity                    1.0000
dtype: float64

In [5]:
user_table = []
properties_table = []
for i, unit in enumerate(['imperial', 'si']):

    user_table.append(
        user_table_prepare(
            pd.DataFrame(user_array[i]),
            unit
        )
    )

    properties_table.append(
        prop_table_units_handler(
            pd.DataFrame(properties_table_raw[i]),
            unit
        )
    )

In [6]:
imperial = calculate_total_piping(Piping_Segment, Air, user_table[0], properties_table[0])
si = calculate_total_piping(Piping_Segment, Air, user_table[1], properties_table[1])

results_imperial = final_table_units_handler(imperial, 'imperial')
results_si = final_table_units_handler(si, 'imperial')

In [7]:
results_imperial

,Segment Length [ft],Temperature Inlet [F],Temperature Outlet [F],Surface Temperature Inlet [F],Surface Temperature Outlet [F],Heat Transfer Total [BTU/h.ft],Heat Transfer by Radiation [BTU/h.ft],Heat Transfer by Convection [BTU/h.ft]
0,831.0,1800.00,1766.62,328.27,324.92,970.16,616.47,419.14
1,2727.0,1766.62,1684.68,318.84,310.66,725.84,452.83,325.36
2,207.0,1684.68,1680.38,300.75,300.33,501.86,305.16,235.97

In [8]:
results_si

,Segment Length [ft],Temperature Inlet [F],Temperature Outlet [F],Surface Temperature Inlet [F],Surface Temperature Outlet [F],Heat Transfer Total [BTU/h.ft],Heat Transfer by Radiation [BTU/h.ft],Heat Transfer by Convection [BTU/h.ft]
0,830.05,1799.60,1766.24,328.34,324.98,970.60,616.77,419.27
1,2726.38,1766.24,1684.26,318.91,310.72,726.15,453.05,325.46
2,206.69,1684.26,1679.97,300.80,300.39,502.07,305.30,236.04

There is a rounding error, due to not providing exatly 1 to 1 properties in SI.

Original values

In [9]:
properties_table_raw[0]

inlet_temperature          1800.000
ambient_temperature          68.000
mass_flow_rate            24155.000
specific_heat_capacity        1.000
k_pipe                        9.700
k_insulation                  0.025
solar_flux                   50.000
emissivity                    1.000
dtype: float64

---
Values handled by prop_table function

In [10]:
prop_table_units_handler(properties_table_raw[1].to_frame(), 'si')

inlet_temperature          1799.600000
ambient_temperature          68.000000
mass_flow_rate            24154.967460
specific_heat_capacity        0.999809
k_pipe                        9.706887
k_insulation                  0.025018
solar_flux                   49.998336
emissivity                    1.000000
Name: Values, dtype: float64